In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [10]:
# Array with 3 elements, all equal to 1
x1 = np.array([1,1,1])
print(x1)

# anther way
x2 =np.ones(3)
print(x2)


[1 1 1]
[1. 1. 1.]


## Q#2: Create y array with elements equal to 0.

In [15]:
# Array with  elements, all equal to 0
y1 = np.zeros(3) 
print(y1)

#anther way
y2 = np.array([0,0,0])
print(y2)

[0. 0. 0.]
[0 0 0]


## Q#3: Add x and y arrays.

In [16]:
Add_Array = x1 + y1  
print(Add_Array)

[1. 1. 1.]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [17]:
print("Dimension:", x1.ndim)
print("Shape:", x1.shape)
print("Size:", x1.size)
print("Type:", x1.dtype)

Dimension: 1
Shape: (3,)
Size: 3
Type: int32


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [18]:
w = np.array([[11, 12 ],
              [13, 14 ], 
              [15, 16]])

print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [19]:
z = np.arange(1, 4)

print(z)

[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [24]:

New_Array1 = np.hstack((z.reshape(-1, 1), w))

#anther way
z_reshaped = z[:, np.newaxis]
New_Array2  = np.concatenate((z_reshaped, w), axis=1)

print("New_Array1")
print(New_Array1)
print("New_Array2")
print(New_Array2)

New_Array1
[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]
New_Array2
[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [25]:
for row in New_Array1:
    for i in row:
        print(i, end=" ")
    print()  # Print a new line after each row


1 11 12 
2 13 14 
3 15 16 


## Q#9: Reverse the columns and rows of "newArray".

In [39]:
New_Array1 = New_Array1[::-1, ::-1]

print(New_Array1)


[[16 15  3]
 [14 13  2]
 [12 11  1]]


## Q#10: Decrement all elements of "newArray" with 1.

In [40]:
New_Array1 = New_Array1 - 1

print(New_Array1)


[[15 14  2]
 [13 12  1]
 [11 10  0]]


## Q#11: Find smallest and biggest values in "newArray".

In [41]:
smallest_value = np.amin(New_Array1)
largest_value = np.amax(New_Array1)

print("Smallest value:", smallest_value)
print("Largest value:", largest_value)


Smallest value: 0
Largest value: 15


## Q#12: Print the first row of "newArray" using indexing.

In [42]:
firstRrow = New_Array1[0]

print(firstRrow)


[15 14  2]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [43]:
target_value = 12

indices = np.where(New_Array1 == target_value)

print("Indices of", target_value, ":", indices)

for idx in zip(indices[0], indices[1]):
    print("Value", target_value, "found at index", idx)



Indices of 12 : (array([1], dtype=int64), array([1], dtype=int64))
Value 12 found at index (1, 1)


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [45]:
targets = [0, 13]

for target_value in targets:

    indices = np.where(New_Array1 == target_value)

    print("Indices of", target_value, ":", indices)

    
    for idx in zip(indices[0], indices[1]):
        print("Value", target_value, "found at index", idx)



Indices of 0 : (array([2], dtype=int64), array([2], dtype=int64))
Value 0 found at index (2, 2)
Indices of 13 : (array([1], dtype=int64), array([0], dtype=int64))
Value 13 found at index (1, 0)


## Q#15: Change the shape of "newArray" to (9,1).

In [46]:
New_Array1 = New_Array1.reshape(9, 1)

print(New_Array1)


[[15]
 [14]
 [ 2]
 [13]
 [12]
 [ 1]
 [11]
 [10]
 [ 0]]


## Q#16: Change the shape of "newArray" to (3,2).

In [50]:
New_Array1 = New_Array1.reshape(3, 3)

print(New_Array1)


[[15 14  2]
 [13 12  1]
 [11 10  0]]


# Well Done 🎉